#!/usr/bin/env python3

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Generate the docs-site README include from the repository README."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Sequence
from urllib.parse import quote, urlparse

REPOSITORY_URL = "https://github.com/CiscoDevNet/sccfm-devkit"
DEFAULT_SOURCE = Path("README.md")
DEFAULT_OUTPUT = Path("docs/_includes/repository-readme.md")
GENERATED_HEADER = "<!-- Generated by `sync-docs-readme`; do not edit by hand. -->"
HEADING_RE = re.compile(r"^(#{1,5})(\s+.+)$")
MARKDOWN_IMAGE_RE = re.compile(r"!\[[^\]]*\]\([^)]+\)")
MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")


class ReadmeSyncError(ValueError):
    """Raised when the README include cannot be generated."""


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _shift_headings(markdown: str) -> str:
    return "\n".join(
        HEADING_RE.sub(lambda match: f"#{match.group(1)}{match.group(2)}", line)
        for line in markdown.splitlines()
    )


def _strip_images(markdown: str) -> str:
    return "\n".join(MARKDOWN_IMAGE_RE.sub("", line).rstrip() for line in markdown.splitlines())


def _is_external_target(target: str) -> bool:
    parsed = urlparse(target)
    return bool(parsed.scheme or parsed.netloc)


def _repository_target(path: str) -> str:
    normalized = path.lstrip("/")
    kind = "blob" if Path(normalized).suffix else "tree"
    return f"{REPOSITORY_URL}/{kind}/main/{quote(normalized)}"


def _rewrite_link_target(target: str) -> str:
    if not target or target.startswith("#") or _is_external_target(target):
        return target

    parsed = urlparse(target)
    if not parsed.path:
        return target

    rewritten = _repository_target(parsed.path)
    if parsed.fragment:
        rewritten = f"{rewritten}#{parsed.fragment}"
    return rewritten


def _rewrite_relative_links(markdown: str) -> str:
    def replace(match: re.Match[str]) -> str:
        label = match.group(1)
        target = match.group(2)
        return f"[{label}]({_rewrite_link_target(target)})"

    return MARKDOWN_LINK_RE.sub(replace, markdown)


def render_include(readme: str) -> str:
    """Return README content suitable for inclusion in the docs homepage."""
    markdown = _rewrite_relative_links(_shift_headings(_strip_images(readme.strip())))
    return f"{GENERATED_HEADER}\n\n{markdown}\n"


def sync_readme(source: Path, output: Path) -> None:
    if not source.is_file():
        raise ReadmeSyncError(f"README source not found: {source}")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_include(source.read_text(encoding="utf-8")), encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate the docs README include.")
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help="Repository README file to embed.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output include path for the docs site.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    project_root = _project_root()
    source = args.source if args.source.is_absolute() else project_root / args.source
    output = args.output if args.output.is_absolute() else project_root / args.output

    try:
        sync_readme(source, output)
    except ReadmeSyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"Generated docs README include in {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
