commitizen:
  name: cz_conventional_commits
  version_provider: pep621
  tag_format: v$version
  update_changelog_on_bump: false
  version_files:
    - sccfm-ansible/plugins/module_utils/dependencies.py:_PAIRED_DEVKIT_REQUIREMENT
