# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pathlib import Path

from cisco_sccfm_scripts import sync_docs_readme


def test_render_include_shifts_headings_and_rewrites_relative_links() -> None:
    readme = (
        "# sccfm-devkit "
        "![CI](https://github.com/example/project/actions/workflows/ci.yml/badge.svg)\n\n"
        "See [docs](docs/README.md), [commands](cisco_sccfm_cli/commands/), "
        "and [setup](#setup).\n"
        "See [auth](https://developer.cisco.com/docs/example/).\n\n"
        "## Setup\n"
    )

    rendered = sync_docs_readme.render_include(readme)

    assert rendered.startswith("<!-- Generated by `sync-docs-readme`; do not edit by hand. -->")
    assert "\n## sccfm-devkit\n" in rendered
    assert "\n### Setup\n" in rendered
    assert "![" not in rendered
    assert (
        "[docs](https://github.com/cisco-lockhart/sccfm-devkit/blob/main/docs/README.md)"
        in rendered
    )
    assert (
        "[commands](https://github.com/cisco-lockhart/sccfm-devkit/tree/main/"
        "cisco_sccfm_cli/commands/)" in rendered
    )
    assert "[setup](#setup)" in rendered
    assert "[auth](https://developer.cisco.com/docs/example/)" in rendered


def test_sync_readme_writes_generated_include(tmp_path: Path) -> None:
    source = tmp_path / "README.md"
    output = tmp_path / "docs" / "_includes" / "repository-readme.md"
    source.write_text("# Title\n\nSee [INSTALL](INSTALL.md).\n", encoding="utf-8")

    sync_docs_readme.sync_readme(source, output)

    assert output.read_text(encoding="utf-8") == (
        "<!-- Generated by `sync-docs-readme`; do not edit by hand. -->\n\n"
        "## Title\n\n"
        "See [INSTALL](https://github.com/cisco-lockhart/sccfm-devkit/blob/main/"
        "INSTALL.md).\n"
    )
