.TH "SCCFM-CLI INVENTORY DEVICES FTD" "1" "2026-08-11" "0.38.0" "sccfm-cli inventory devices ftd Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-ftd \- FTD device operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices ftd
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
FTD device operations.
.SH COMMANDS
\fBlist\fP
  List FTD devices (includes cdFMC-managed,...
  See \fBsccfm-cli inventory devices ftd-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBlist-not-on-version\fP
  List FTD devices that are NOT running a...
  See \fBsccfm-cli inventory devices ftd-list-not-on-version(1)\fP for full documentation on the \fBlist-not-on-version\fP command.
.PP
\fBupgrade\fP
  FTD device upgrade operations.
  See \fBsccfm-cli inventory devices ftd-upgrade(1)\fP for full documentation on the \fBupgrade\fP command.
