.TH "SCCFM-CLI OBJECTS NETWORK-GROUP LIST" "1" "2026-06-04" "0.37.0" "sccfm-cli objects network-group list Manual"
.SH NAME
sccfm-cli\-objects\-network-group\-list \- List network groups.
.SH SYNOPSIS
.B sccfm-cli objects network-group list
[OPTIONS]
.SH DESCRIPTION
List network groups.
.SH OPTIONS
.TP
\fB\-l,\fP \-\-limit INTEGER RANGE
Maximum records to return  [default: 50; 1<=x<=200]
.TP
\fB\-o,\fP \-\-offset INTEGER RANGE
Pagination offset  [default: 0; x>=0]
.TP
\fB\-q,\fP \-\-query TEXT
Lucene query string. Searchable fields: name, content.
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
