.TH "SCCFM-CLI POLICIES ACCESS-RULE DELETE" "1" "2026-08-24" "0.39.5" "sccfm-cli policies access-rule delete Manual"
.SH NAME
sccfm-cli\-policies\-access-rule\-delete \- Delete an ASA access rule.
.SH SYNOPSIS
.B sccfm-cli policies access-rule delete
[OPTIONS]
.SH DESCRIPTION
Delete an ASA access rule.
.SH OPTIONS
.TP
\fB\-\-uid\fP TEXT
UID of the access rule to delete.  [required]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
