.TH "SCCFM-CLI INVENTORY MANAGER" "1" "2026-08-18" "0.39.1" "sccfm-cli inventory manager Manual"
.SH NAME
sccfm-cli\-inventory\-manager \- Manager inventory operations.
.SH SYNOPSIS
.B sccfm-cli inventory manager
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manager inventory operations.
.SH COMMANDS
\fBlist\fP
  List manager.
  See \fBsccfm-cli inventory manager-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBaccess-policies\fP
  FMC access policy operations.
  See \fBsccfm-cli inventory manager-access-policies(1)\fP for full documentation on the \fBaccess-policies\fP command.
