.TH "SCCFM-CLI POLICIES ACCESS-GROUP" "1" "2026-08-19" "0.39.2" "sccfm-cli policies access-group Manual"
.SH NAME
sccfm-cli\-policies\-access-group \- List and inspect ASA access groups.
.SH SYNOPSIS
.B sccfm-cli policies access-group
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
List and inspect ASA access groups.
.SH COMMANDS
\fBget\fP
  Get an ASA access group by UID.
  See \fBsccfm-cli policies access-group-get(1)\fP for full documentation on the \fBget\fP command.
.PP
\fBlist\fP
  List ASA access groups.
  See \fBsccfm-cli policies access-group-list(1)\fP for full documentation on the \fBlist\fP command.
