.TH "SCCFM-CLI INVENTORY DEVICES ASA CLI" "1" "2026-08-11" "0.38.0" "sccfm-cli inventory devices asa cli Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-asa\-cli \- ASA device CLI operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices asa cli
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
ASA device CLI operations.
.SH COMMANDS
\fBexecute\fP
  Execute CLI commands on ASA devices.
  See \fBsccfm-cli inventory devices asa cli-execute(1)\fP for full documentation on the \fBexecute\fP command.
