.TH "SCCFM-CLI OBJECTS NETWORK" "1" "2026-08-19" "0.39.3" "sccfm-cli objects network Manual"
.SH NAME
sccfm-cli\-objects\-network \- Manage network objects.
.SH SYNOPSIS
.B sccfm-cli objects network
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage network objects.
.SH COMMANDS
\fBcreate\fP
  Create a network object.
  See \fBsccfm-cli objects network-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBlist\fP
  List network objects.
  See \fBsccfm-cli objects network-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBupdate\fP
  Update a network object.
  See \fBsccfm-cli objects network-update(1)\fP for full documentation on the \fBupdate\fP command.
.PP
\fBdelete\fP
  Delete a network object.
  See \fBsccfm-cli objects network-delete(1)\fP for full documentation on the \fBdelete\fP command.
