.TH "SCCFM-CLI OBJECTS NETWORK LIST" "1" "2026-08-18" "0.39.0" "sccfm-cli objects network list Manual"
.SH NAME
sccfm-cli\-objects\-network\-list \- List network objects.
.SH SYNOPSIS
.B sccfm-cli objects network list
[OPTIONS]
.SH DESCRIPTION
List network objects.
.SH OPTIONS
.TP
\fB\-l,\fP \-\-limit INTEGER RANGE
Maximum records to return  [default: 50; 1<=x<=200]
.TP
\fB\-o,\fP \-\-offset INTEGER RANGE
Pagination offset  [default: 0; x>=0]
.TP
\fB\-q,\fP \-\-query TEXT
Lucene query string. Searchable fields: name, content.
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
