.TH "SCCFM-CLI POLICIES ACCESS-RULE" "1" "2026-08-27" "0.40.0" "sccfm-cli policies access-rule Manual"
.SH NAME
sccfm-cli\-policies\-access-rule \- Manage ASA access rules.
.SH SYNOPSIS
.B sccfm-cli policies access-rule
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage ASA access rules.
.SH COMMANDS
\fBcreate\fP
  Create an ASA access rule.
  See \fBsccfm-cli policies access-rule-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBget\fP
  Get an ASA access rule by UID.
  See \fBsccfm-cli policies access-rule-get(1)\fP for full documentation on the \fBget\fP command.
.PP
\fBlist\fP
  List ASA access rules.
  See \fBsccfm-cli policies access-rule-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBupdate\fP
  Update an ASA access rule.
  See \fBsccfm-cli policies access-rule-update(1)\fP for full documentation on the \fBupdate\fP command.
.PP
\fBdelete\fP
  Delete an ASA access rule.
  See \fBsccfm-cli policies access-rule-delete(1)\fP for full documentation on the \fBdelete\fP command.
