.TH "SCCFM-CLI STATUS" "1" "2026-08-27" "0.40.1" "sccfm-cli status Manual"
.SH NAME
sccfm-cli\-status \- Display the state of SCCFM subsystems.
.SH SYNOPSIS
.B sccfm-cli status
[OPTIONS]
.SH DESCRIPTION
Display the state of SCCFM subsystems.
.SH OPTIONS
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
