.TH "SCCFM-CLI OBJECTS" "1" "2026-08-27" "0.40.1" "sccfm-cli objects Manual"
.SH NAME
sccfm-cli\-objects \- Manage SCC Firewall Management objects.
.SH SYNOPSIS
.B sccfm-cli objects
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage SCC Firewall Management objects.
.SH COMMANDS
\fBnetwork\fP
  Manage network objects.
  See \fBsccfm-cli objects-network(1)\fP for full documentation on the \fBnetwork\fP command.
.PP
\fBnetwork-group\fP
  Manage network group objects.
  See \fBsccfm-cli objects-network-group(1)\fP for full documentation on the \fBnetwork-group\fP command.
.PP
\fBadd-override\fP
  Add a device-specific override to an object.
  See \fBsccfm-cli objects-add-override(1)\fP for full documentation on the \fBadd-override\fP command.
.PP
\fBupdate-default\fP
  Update the default content value of an...
  See \fBsccfm-cli objects-update-default(1)\fP for full documentation on the \fBupdate-default\fP command.
.PP
\fBedit-override\fP
  Edit the value of an existing override for...
  See \fBsccfm-cli objects-edit-override(1)\fP for full documentation on the \fBedit-override\fP command.
.PP
\fBdelete-override\fP
  Delete an existing override for a specific...
  See \fBsccfm-cli objects-delete-override(1)\fP for full documentation on the \fBdelete-override\fP command.
.PP
\fBapply-override-as-default\fP
  Apply an existing override value as the...
  See \fBsccfm-cli objects-apply-override-as-default(1)\fP for full documentation on the \fBapply-override-as-default\fP command.
.PP
\fBshow\fP
  Show the full details of an object,...
  See \fBsccfm-cli objects-show(1)\fP for full documentation on the \fBshow\fP command.
