.TH "SCCFM-CLI OBJECTS NETWORK-GROUP" "1" "2026-06-02" "0.36.0" "sccfm-cli objects network-group Manual"
.SH NAME
sccfm-cli\-objects\-network-group \- Manage network group objects.
.SH SYNOPSIS
.B sccfm-cli objects network-group
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage network group objects.
.SH COMMANDS
\fBcreate\fP
  Create a network group.
  See \fBsccfm-cli objects network-group-create(1)\fP for full documentation on the \fBcreate\fP command.
.PP
\fBlist\fP
  List network groups.
  See \fBsccfm-cli objects network-group-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBadd-member\fP
  Add referenced network-object members to a...
  See \fBsccfm-cli objects network-group-add-member(1)\fP for full documentation on the \fBadd-member\fP command.
.PP
\fBremove-member\fP
  Remove referenced network-object members...
  See \fBsccfm-cli objects network-group-remove-member(1)\fP for full documentation on the \fBremove-member\fP command.
.PP
\fBupdate\fP
  Update a network group.
  See \fBsccfm-cli objects network-group-update(1)\fP for full documentation on the \fBupdate\fP command.
.PP
\fBdelete\fP
  Delete a network group object.
  See \fBsccfm-cli objects network-group-delete(1)\fP for full documentation on the \fBdelete\fP command.
