.TH "SCCFM-CLI INVENTORY DEVICES CDFMC-MANAGED-FTD CLI" "1" "2026-08-27" "0.40.0" "sccfm-cli inventory devices cdfmc-managed-ftd cli Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-cdfmc-managed-ftd\-cli \- cdFMC-managed FTD device CLI operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices cdfmc-managed-ftd cli
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
cdFMC-managed FTD device CLI operations.
.SH COMMANDS
\fBexecute\fP
  Execute a show command on cdFMC-managed...
  See \fBsccfm-cli inventory devices cdfmc-managed-ftd cli-execute(1)\fP for full documentation on the \fBexecute\fP command.
