.TH "SCCFM-CLI INVENTORY DEVICES ASA DISK" "1" "2026-08-27" "0.40.0" "sccfm-cli inventory devices asa disk Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-asa\-disk \- ASA device disk operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices asa disk
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
ASA device disk operations.
.SH COMMANDS
\fBlist-files\fP
  List OS, AnyConnect, and ASDM files on ASA...
  See \fBsccfm-cli inventory devices asa disk-list-files(1)\fP for full documentation on the \fBlist-files\fP command.
