.TH "SCCFM-CLI INVENTORY DEVICES ASA SHUN" "1" "2026-08-18" "0.39.0" "sccfm-cli inventory devices asa shun Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-asa\-shun \- Manage shun entries on ASA devices.
.SH SYNOPSIS
.B sccfm-cli inventory devices asa shun
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage shun entries on ASA devices.
.SH COMMANDS
\fBadd\fP
  Shun (block) one or more source IP...
  See \fBsccfm-cli inventory devices asa shun-add(1)\fP for full documentation on the \fBadd\fP command.
.PP
\fBshow\fP
  Display active shun entries on ASA devices.
  See \fBsccfm-cli inventory devices asa shun-show(1)\fP for full documentation on the \fBshow\fP command.
.PP
\fBremove\fP
  Remove one or more shun entries from ASA...
  See \fBsccfm-cli inventory devices asa shun-remove(1)\fP for full documentation on the \fBremove\fP command.
.PP
\fBclear\fP
  Disable all active shuns and clear shun...
  See \fBsccfm-cli inventory devices asa shun-clear(1)\fP for full documentation on the \fBclear\fP command.
