.TH "SCCFM-CLI POLICIES ACCESS-RULE GET" "1" "2026-08-19" "0.39.2" "sccfm-cli policies access-rule get Manual"
.SH NAME
sccfm-cli\-policies\-access-rule\-get \- Get an ASA access rule by UID.
.SH SYNOPSIS
.B sccfm-cli policies access-rule get
[OPTIONS]
.SH DESCRIPTION
Get an ASA access rule by UID.
.SH OPTIONS
.TP
\fB\-\-uid\fP TEXT
UID of the access rule.  [required]
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
