.TH "SCCFM-CLI INVENTORY" "1" "2026-08-19" "0.39.3" "sccfm-cli inventory Manual"
.SH NAME
sccfm-cli\-inventory \- Browse SCC Firewall Management inventory.
.SH SYNOPSIS
.B sccfm-cli inventory
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Browse SCC Firewall Management inventory.
.SH COMMANDS
\fBdevices\fP
  Device inventory operations.
  See \fBsccfm-cli inventory-devices(1)\fP for full documentation on the \fBdevices\fP command.
.PP
\fBmanager\fP
  Manager inventory operations.
  See \fBsccfm-cli inventory-manager(1)\fP for full documentation on the \fBmanager\fP command.
