.TH "SCCFM-CLI SCHEMA" "1" "2026-08-26" "0.40.0" "sccfm-cli schema Manual"
.SH NAME
sccfm-cli\-schema \- Export machine-readable command metadata.
.SH SYNOPSIS
.B sccfm-cli schema
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Export machine-readable command metadata.
.SH COMMANDS
\fBexport\fP
  Export the sccfm-cli command schema.
  See \fBsccfm-cli schema-export(1)\fP for full documentation on the \fBexport\fP command.
