.TH "SCCFM-CLI INVENTORY DEVICES ASA" "1" "2026-06-19" "0.38.0" "sccfm-cli inventory devices asa Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-asa \- ASA device operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices asa
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
ASA device operations.
.SH COMMANDS
\fBchange-boot-image\fP
  Change the configured ASA boot image for...
  See \fBsccfm-cli inventory devices asa-change-boot-image(1)\fP for full documentation on the \fBchange-boot-image\fP command.
.PP
\fBcli\fP
  ASA device CLI operations.
  See \fBsccfm-cli inventory devices asa-cli(1)\fP for full documentation on the \fBcli\fP command.
.PP
\fBdisk\fP
  ASA device disk operations.
  See \fBsccfm-cli inventory devices asa-disk(1)\fP for full documentation on the \fBdisk\fP command.
.PP
\fBha-check\fP
  Run HA health checks on ASA failover pairs.
  See \fBsccfm-cli inventory devices asa-ha-check(1)\fP for full documentation on the \fBha-check\fP command.
.PP
\fBlist\fP
  List ASA devices.
  See \fBsccfm-cli inventory devices asa-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBlist-boot-registry\fP
  Show boot registry info (system image,...
  See \fBsccfm-cli inventory devices asa-list-boot-registry(1)\fP for full documentation on the \fBlist-boot-registry\fP command.
.PP
\fBlist-not-on-version\fP
  List ASA devices that are NOT running a...
  See \fBsccfm-cli inventory devices asa-list-not-on-version(1)\fP for full documentation on the \fBlist-not-on-version\fP command.
.PP
\fBsmartlicense\fP
  Apply Smart License using a Smart license...
  See \fBsccfm-cli inventory devices asa-smartlicense(1)\fP for full documentation on the \fBsmartlicense\fP command.
.PP
\fBonboard\fP
  Onboard an ASA device to SCC Firewall...
  See \fBsccfm-cli inventory devices asa-onboard(1)\fP for full documentation on the \fBonboard\fP command.
.PP
\fBlist-local-users\fP
  List local users on ASA devices.
  See \fBsccfm-cli inventory devices asa-list-local-users(1)\fP for full documentation on the \fBlist-local-users\fP command.
.PP
\fBshun\fP
  Manage shun entries on ASA devices.
  See \fBsccfm-cli inventory devices asa-shun(1)\fP for full documentation on the \fBshun\fP command.
.PP
\fBupgrade\fP
  ASA device upgrade operations.
  See \fBsccfm-cli inventory devices asa-upgrade(1)\fP for full documentation on the \fBupgrade\fP command.
.PP
\fBuser\fP
  ASA local user operations.
  See \fBsccfm-cli inventory devices asa-user(1)\fP for full documentation on the \fBuser\fP command.
