.TH "SCCFM-CLI INVENTORY DEVICES FTD UPGRADE" "1" "2026-09-01" "0.40.1" "sccfm-cli inventory devices ftd upgrade Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-ftd\-upgrade \- FTD device upgrade operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices ftd upgrade
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
FTD device upgrade operations.
.SH COMMANDS
\fBcompatible-versions\fP
  List software versions compatible with a...
  See \fBsccfm-cli inventory devices ftd upgrade-compatible-versions(1)\fP for full documentation on the \fBcompatible-versions\fP command.
.PP
\fBtrigger\fP
  Trigger an FTD firmware upgrade on one or...
  See \fBsccfm-cli inventory devices ftd upgrade-trigger(1)\fP for full documentation on the \fBtrigger\fP command.
