.TH "SCCFM-CLI INVENTORY DEVICES ASA UPGRADE" "1" "2026-08-27" "0.40.1" "sccfm-cli inventory devices asa upgrade Manual"
.SH NAME
sccfm-cli\-inventory\-devices\-asa\-upgrade \- ASA device upgrade operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices asa upgrade
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
ASA device upgrade operations.
.SH COMMANDS
\fBcompatible-versions\fP
  List software versions compatible with a...
  See \fBsccfm-cli inventory devices asa upgrade-compatible-versions(1)\fP for full documentation on the \fBcompatible-versions\fP command.
.PP
\fBtrigger\fP
  Trigger an ASA firmware/ASDM upgrade on...
  See \fBsccfm-cli inventory devices asa upgrade-trigger(1)\fP for full documentation on the \fBtrigger\fP command.
