.TH "SCCFM-CLI INVENTORY DEVICES" "1" "2026-08-19" "0.39.2" "sccfm-cli inventory devices Manual"
.SH NAME
sccfm-cli\-inventory\-devices \- Device inventory operations.
.SH SYNOPSIS
.B sccfm-cli inventory devices
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Device inventory operations.
.SH COMMANDS
\fBasa\fP
  ASA device operations.
  See \fBsccfm-cli inventory devices-asa(1)\fP for full documentation on the \fBasa\fP command.
.PP
\fBftd\fP
  FTD device operations.
  See \fBsccfm-cli inventory devices-ftd(1)\fP for full documentation on the \fBftd\fP command.
.PP
\fBcdfmc-managed-ftd\fP
  cdFMC-managed FTD device operations.
  See \fBsccfm-cli inventory devices-cdfmc-managed-ftd(1)\fP for full documentation on the \fBcdfmc-managed-ftd\fP command.
.PP
\fBlist\fP
  List devices.
  See \fBsccfm-cli inventory devices-list(1)\fP for full documentation on the \fBlist\fP command.
