.TH "SCCFM-CLI OBJECTS NETWORK-GROUP REMOVE-MEMBER" "1" "2026-06-19" "0.38.0" "sccfm-cli objects network-group remove-member Manual"
.SH NAME
sccfm-cli\-objects\-network-group\-remove-member \- Remove referenced network-object members...
.SH SYNOPSIS
.B sccfm-cli objects network-group remove-member
[OPTIONS]
.SH DESCRIPTION
Remove referenced network-object members from a network group.
.SH OPTIONS
.TP
\fB\-u,\fP \-\-uid TEXT
The unique identifier (UID) of the object.
.TP
\fB\-n,\fP \-\-name TEXT
The name of the object (alternative to UID).
.TP
\fB\-r,\fP \-\-referenced\-object TEXT
UID or name of an existing network object to include (repeatable).
.TP
\fB\-\-check\fP
Run a preflight check without performing the operation.
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
