.TH "SCCFM-CLI INVENTORY MANAGER LIST" "1" "2026-08-27" "0.40.0" "sccfm-cli inventory manager list Manual"
.SH NAME
sccfm-cli\-inventory\-manager\-list \- List manager.
.SH SYNOPSIS
.B sccfm-cli inventory manager list
[OPTIONS]
.SH DESCRIPTION
List manager.
.SH OPTIONS
.TP
\fB\-l,\fP \-\-limit INTEGER RANGE
Maximum records to return  [default: 50; 1<=x<=200]
.TP
\fB\-o,\fP \-\-offset INTEGER RANGE
Pagination offset  [default: 0; x>=0]
.TP
\fB\-q,\fP \-\-query TEXT
The query to execute. Use the Lucene Query Syntax to construct your query.
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
