.TH "SCCFM-CLI POLICIES" "1" "2026-06-19" "0.38.0" "sccfm-cli policies Manual"
.SH NAME
sccfm-cli\-policies \- Manage SCC Firewall Management policies.
.SH SYNOPSIS
.B sccfm-cli policies
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Manage SCC Firewall Management policies.
.SH COMMANDS
\fBaccess-group\fP
  List and inspect ASA access groups.
  See \fBsccfm-cli policies-access-group(1)\fP for full documentation on the \fBaccess-group\fP command.
.PP
\fBaccess-rule\fP
  Manage ASA access rules.
  See \fBsccfm-cli policies-access-rule(1)\fP for full documentation on the \fBaccess-rule\fP command.
