.TH "SCCFM-CLI OBJECTS DELETE-OVERRIDE" "1" "2026-08-18" "0.39.1" "sccfm-cli objects delete-override Manual"
.SH NAME
sccfm-cli\-objects\-delete-override \- Delete an existing override for a specific...
.SH SYNOPSIS
.B sccfm-cli objects delete-override
[OPTIONS]
.SH DESCRIPTION
Delete an existing override for a specific target device.
.SH OPTIONS
.TP
\fB\-u,\fP \-\-uid TEXT
The unique identifier (UID) of the object.
.TP
\fB\-\-target\-id\fP TEXT
UID of the target device whose override to delete.  [required]
.TP
\fB\-\-format\fP [table|json]
Output format  [default: table]
.TP
\fB\-\-config\-path\fP PATH
Path to the configuration file (defaults to ~/.sccfm-cli/config.json).
