.TH "SCCFM-CLI INVENTORY MANAGER ACCESS-POLICIES" "1" "2026-08-26" "0.40.0" "sccfm-cli inventory manager access-policies Manual"
.SH NAME
sccfm-cli\-inventory\-manager\-access-policies \- FMC access policy operations.
.SH SYNOPSIS
.B sccfm-cli inventory manager access-policies
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
FMC access policy operations.
.SH COMMANDS
\fBlist\fP
  List FMC access policies for a given domain.
  See \fBsccfm-cli inventory manager access-policies-list(1)\fP for full documentation on the \fBlist\fP command.
