---
# Plain variables (not sensitive)
# These can be committed to version control

# SCCFM connection settings
sccfm_region: int

# Common ASA configuration
default_asa_username: admin
default_ignore_certificate: true

# Default connector settings
default_connector_type: SDC
