#!/usr/bin/env python3

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Generate Ansible documentation previews from ansible-doc output."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Mapping, Sequence

COLLECTION_FQCN = "cisco.sccfm"
DEFAULT_OUTPUT_DIR = Path("docs/ansible")
GENERATED_HEADER = "<!-- Generated by `generate-ansible-docs`; do not edit by hand. -->"
ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")


class OutputDirectoryError(ValueError):
    """Raised when an output directory cannot be safely replaced."""


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _ansible_doc_executable() -> str:
    if executable := shutil.which("ansible-doc"):
        return executable

    venv_executable = Path(sys.executable).parent / "ansible-doc"
    if venv_executable.is_file():
        return str(venv_executable)

    raise RuntimeError(
        "ansible-doc not found. Activate the project virtualenv or install ansible-core."
    )


@contextmanager
def _source_collection_path(project_root: Path) -> Iterator[Path]:
    collection_dir = project_root / "sccfm-ansible"
    if not collection_dir.is_dir():
        raise FileNotFoundError(f"Collection directory not found: {collection_dir}")

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        namespace_dir = root / "ansible_collections" / "cisco"
        namespace_dir.mkdir(parents=True)
        (namespace_dir / "sccfm").symlink_to(collection_dir, target_is_directory=True)
        yield root


def _run_ansible_doc(project_root: Path, collection_path: Path, args: Sequence[str]) -> str:
    env = os.environ.copy()
    env["ANSIBLE_COLLECTIONS_PATH"] = str(collection_path)
    env["ANSIBLE_NOCOLOR"] = "1"
    env["NO_COLOR"] = "1"
    env.pop("ANSIBLE_FORCE_COLOR", None)
    result = subprocess.run(
        [_ansible_doc_executable(), *args],
        cwd=project_root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "ansible-doc failed with exit code "
            f"{result.returncode}\nSTDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )
    return _clean_ansible_doc_output(result.stdout.strip(), project_root, collection_path)


def _clean_ansible_doc_output(output: str, project_root: Path, collection_path: Path) -> str:
    return _strip_ansi_sequences(_normalize_source_paths(output, project_root, collection_path))


def _strip_ansi_sequences(output: str) -> str:
    return ANSI_ESCAPE_RE.sub("", output)


def _normalize_source_paths(output: str, project_root: Path, collection_path: Path) -> str:
    source_roots = [
        collection_path / "ansible_collections" / "cisco" / "sccfm",
        project_root / "sccfm-ansible",
    ]
    normalized = output
    for source_root in source_roots:
        normalized = normalized.replace(str(source_root), "sccfm-ansible")
    return normalized


def _list_plugins(project_root: Path, collection_path: Path, plugin_type: str) -> list[str]:
    output = _run_ansible_doc(
        project_root,
        collection_path,
        ["-l", "-t", plugin_type, COLLECTION_FQCN],
    )
    plugins: list[str] = []
    for line in output.splitlines():
        name = line.split(maxsplit=1)[0] if line.strip() else ""
        if name.startswith(f"{COLLECTION_FQCN}.") and f"{COLLECTION_FQCN}.tests." not in name:
            plugins.append(name)
    return sorted(plugins)


def _render_page(fqcn: str, command: str, output: str) -> str:
    return (
        f"{GENERATED_HEADER}\n\n# {fqcn}\n\n"
        "{% raw %}\n"
        f"```text\n$ {command}\n\n{output}\n```\n"
        "{% endraw %}\n"
    )


def _link(plugin_type: str, fqcn: str) -> str:
    name = fqcn.removeprefix(f"{COLLECTION_FQCN}.")
    return f"- [{fqcn}]({plugin_type}/{name}.html)"


def _render_index(modules: Sequence[str], inventory_plugins: Sequence[str]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# cisco.sccfm Ansible Reference",
        "",
        "Generated from `ansible-doc` output.",
        "",
        "## Inventory Plugins",
        "",
    ]
    lines.extend(_link("inventory", name) for name in inventory_plugins)
    lines.extend(["", "## Modules", ""])
    lines.extend(_link("modules", name) for name in modules)
    lines.append("")
    return "\n".join(lines)


def _generate_files(project_root: Path, docs_root: Path) -> Mapping[Path, str]:
    with _source_collection_path(project_root) as collection_path:
        modules = _list_plugins(project_root, collection_path, "module")
        inventory_plugins = _list_plugins(project_root, collection_path, "inventory")

        files: dict[Path, str] = {
            docs_root / "index.md": _render_index(modules, inventory_plugins),
        }
        for fqcn in modules:
            output = _run_ansible_doc(project_root, collection_path, ["-t", "module", fqcn])
            name = fqcn.removeprefix(f"{COLLECTION_FQCN}.")
            files[docs_root / "modules" / f"{name}.md"] = _render_page(
                fqcn,
                f"ansible-doc -t module {fqcn}",
                output,
            )
        for fqcn in inventory_plugins:
            output = _run_ansible_doc(project_root, collection_path, ["-t", "inventory", fqcn])
            name = fqcn.removeprefix(f"{COLLECTION_FQCN}.")
            files[docs_root / "inventory" / f"{name}.md"] = _render_page(
                fqcn,
                f"ansible-doc -t inventory {fqcn}",
                output,
            )
        return files


def _validate_output_directory(docs_root: Path, default_docs_root: Path) -> None:
    if not docs_root.exists():
        return
    if not docs_root.is_dir() or docs_root.is_symlink():
        raise OutputDirectoryError(f"Refusing to overwrite non-directory path {docs_root}.")
    if docs_root.resolve() == default_docs_root.resolve():
        return
    if any(docs_root.iterdir()):
        raise OutputDirectoryError(
            f"Refusing to overwrite non-empty custom output directory {docs_root}. "
            "Use the default output directory or choose an empty path."
        )


def _write_files(files: Mapping[Path, str], docs_root: Path, default_docs_root: Path) -> None:
    _validate_output_directory(docs_root, default_docs_root)
    if docs_root.exists():
        shutil.rmtree(docs_root)

    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate Ansible documentation previews.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate that docs can be generated without writing files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for generated Ansible docs.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    project_root = _project_root()
    docs_root = args.output_dir if args.output_dir.is_absolute() else project_root / args.output_dir
    default_docs_root = project_root / DEFAULT_OUTPUT_DIR
    files = _generate_files(project_root, docs_root)

    if args.check:
        print(f"Generated {len(files)} Ansible documentation files in memory")
    else:
        try:
            _write_files(files, docs_root, default_docs_root)
        except OutputDirectoryError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"Generated {len(files)} Ansible documentation files in {docs_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
