#!/usr/bin/env python3

# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

"""Generate CLI documentation previews from Click help output."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Mapping, Sequence

import click
from click.testing import CliRunner

from sccfm_cli.cli import cli

DEFAULT_OUTPUT_DIR = Path("docs/cli")
GENERATED_HEADER = "<!-- Generated by `generate-cli-docs`; do not edit by hand. -->"


class OutputDirectoryError(ValueError):
    """Raised when an output directory cannot be safely replaced."""


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _command_paths(command: click.Command, path: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    paths = [path]
    if isinstance(command, click.Group):
        for name, child in sorted(command.commands.items()):
            paths.extend(_command_paths(child, (*path, name)))
    return paths


def _page_name(path: Sequence[str]) -> str:
    if not path:
        return "sccfm-cli"
    return "sccfm-cli-" + "-".join(path)


def _command_text(path: Sequence[str]) -> str:
    return "sccfm-cli" if not path else "sccfm-cli " + " ".join(path)


def _help_output(path: Sequence[str]) -> str:
    result = CliRunner().invoke(
        cli,
        [*path, "--help"],
        prog_name="sccfm-cli",
        color=False,
    )
    if result.exit_code != 0:
        raise RuntimeError(
            f"{_command_text(path)} --help failed with exit code {result.exit_code}\n"
            f"{result.output}"
        )
    return result.output.strip()


def _render_page(path: Sequence[str], output: str) -> str:
    command = _command_text(path)
    return f"{GENERATED_HEADER}\n\n# {command}\n\n```text\n$ {command} --help\n\n{output}\n```\n"


def _render_index(paths: Sequence[tuple[str, ...]]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# sccfm-cli Reference",
        "",
        "Generated from Click `--help` output.",
        "",
        "## Commands",
        "",
    ]
    for path in paths:
        page = _page_name(path)
        lines.append(f"- [{_command_text(path)}]({page}.html)")
    lines.append("")
    return "\n".join(lines)


def _generate_files(docs_root: Path) -> Mapping[Path, str]:
    paths = _command_paths(cli)
    files: dict[Path, str] = {
        docs_root / "index.md": _render_index(paths),
    }
    for path in paths:
        files[docs_root / f"{_page_name(path)}.md"] = _render_page(path, _help_output(path))
    return files


def _validate_output_directory(docs_root: Path, default_docs_root: Path) -> None:
    if not docs_root.exists():
        return
    if not docs_root.is_dir() or docs_root.is_symlink():
        raise OutputDirectoryError(f"Refusing to overwrite non-directory path {docs_root}.")
    if docs_root.resolve() == default_docs_root.resolve():
        return
    if any(docs_root.iterdir()):
        raise OutputDirectoryError(
            f"Refusing to overwrite non-empty custom output directory {docs_root}. "
            "Use the default output directory or choose an empty path."
        )


def _write_files(files: Mapping[Path, str], docs_root: Path, default_docs_root: Path) -> None:
    _validate_output_directory(docs_root, default_docs_root)
    if docs_root.exists():
        shutil.rmtree(docs_root)
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate CLI documentation previews.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate that docs can be generated without writing files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for generated CLI docs.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    project_root = _project_root()
    docs_root = args.output_dir if args.output_dir.is_absolute() else project_root / args.output_dir
    default_docs_root = project_root / DEFAULT_OUTPUT_DIR
    files = _generate_files(docs_root)

    if args.check:
        print(f"Generated {len(files)} CLI documentation files in memory")
    else:
        try:
            _write_files(files, docs_root, default_docs_root)
        except OutputDirectoryError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        print(f"Generated {len(files)} CLI documentation files in {docs_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
