namespace: cisco
name: sccfm
version: 0.25.0
readme: README.md
authors:
- Cisco Security Cloud Control Firewall Manager Team
description: Ansible inventory plugin for Cisco SCC Firewall Manager (SCCFM).
license_file: LICENSE
tags:
- cisco
- sccfm
- security
- firewall
- cloud
- collection
repository: https://github.com/cisco-lockhart/sccfm-devkit
documentation: https://github.com/cisco-lockhart/sccfm-devkit
homepage: https://github.com/cisco-lockhart/sccfm-devkit
issues: https://github.com/cisco-lockhart/sccfm-devkit/issues
build_ignore:
- .venv
- .pytest_cache
- .mypy_cache
- .idea
- .vscode
- dist
- ansible_collections
