namespace: cisco
name: sccfm
version: 0.38.0
readme: README.md
authors:
- Cisco Security Cloud Control Firewall Manager Team
description: Ansible inventory plugin for Cisco SCC Firewall Manager (SCCFM).
license:
- Apache-2.0
license_file: LICENSE
tags:
- cisco
- sccfm
- security
- firewall
- cloud
- collection
repository: https://github.com/CiscoDevNet/sccfm-devkit
documentation: https://ciscodevnet.github.io/sccfm-devkit/
homepage: https://github.com/CiscoDevNet/sccfm-devkit
issues: https://github.com/CiscoDevNet/sccfm-devkit/issues
build_ignore:
- .venv
- .pytest_cache
- .mypy_cache
- .idea
- .vscode
- dist
- ansible_collections
- plugins/modules/tests
- plugins/modules/tests/**
- .DS_Store
- '**/.DS_Store'
- .gitignore
- build.sh
- __pycache__
- '**/__pycache__'
- '*.pyc'
- '**/*.pyc'
- ci
- e2e
